### ISSUE TITLE
Commenting standard?

### ISSUE THREAD

**Issue by ry5n** [Shopify/css#8]
I’d like a standard way to write inline and block comments, mostly because otherwise I tend to fuss with them. This is my personal preference:

``` scss
//
// This is a Sass block comment
//
.red-bull {
  content: 'bull';
  color: red;
}

//
// Returns the string passed in.
//
// @param {String} $string - A string value.
// @return {String} Your string.
//
@function yoyo($string) {
  @return $string;
}

.some-thing {
  color: black;
  -webkit-font-smoothing: antialiased; // Short comment
}

.some-thing-2 {
  color: black;

  // Long comment that would otherwise wrap and be distracting
  -webkit-font-smoothing: antialiased;
}

//
// Heavily annotated thing. Should be avoided except for obscure or complex 
// browser-wrangling.
// 
// 1. Explanation for the first thing here
// 2. Long comment that would otherwise wrap and be distracting
//
.complex-thing-2 {
  color: black; // 1
  -webkit-font-smoothing: antialiased; // 2
}
```
